### ISSUE TITLE
How to package changes to the app?

### ISSUE THREAD

**Issue by johnsaigle** [ofstudio/djay2itunes.js#3]
Hi! I'm trying to modify this script for my own personal use so that the format is `BPM - Key - Title - Artist`. I've managed to do this in the `main.scpt` file but I'm not sure how to bundle this to be executable. 

What I mean is that to use my modification I have to go to the app -> Show Package Contents -> Find `main.scpt`, open that in xcode and then run it. 

I'd prefer to run the application as you've intended but changing the .js file doesn't seem to do anything.

Would you be able to help me figure this out?

Thanks for this btw; it's really useful!

**Comment by ofstudio** [comment]
To fork / modify you need the [source code](https://raw.githubusercontent.com/ofstudio/djay2itunes.js/master/djay2itunes.js), not app package.

1. Open `/Applications/Utilities/Script Editor.app`
2. Choose "New Document
3. Switch language to from "Applescript" to "Javascript" in top left corner
4. Paste the source code from link above 
5. Modify, test, run code…
6. Save the result to `.scpt` file
7. After that you can export an application: choose `File => Export` and application format.

![screen shot 2017-10-12 at 10 49 34](https://user-images.githubusercontent.com/2184504/31485040-2298524c-af3b-11e7-9501-cf2f7943775f.png)
